/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercise;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;

/**
 *
 * @author 05632593029
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        lblTipoPessoa = new javax.swing.JLabel();
        lblBicicleta = new javax.swing.JLabel();
        lblDataInicio = new javax.swing.JLabel();
        lblDataDevolucao = new javax.swing.JLabel();
        cmbTipoPessoa = new javax.swing.JComboBox<>();
        cmbBicicleta = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        lblValorTotal = new javax.swing.JLabel();
        ftfValorTotal = new javax.swing.JFormattedTextField();
        ftfDataInicio = new javax.swing.JFormattedTextField();
        ftfDataDevolucao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoPessoa.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTipoPessoa.setText("Tipo Pessoa");

        lblBicicleta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBicicleta.setText("Bicicleta");

        lblDataInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDataInicio.setText("Data Início");

        lblDataDevolucao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDataDevolucao.setText("Data Devolução");

        cmbTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudante", "Trabalhador" }));

        cmbBicicleta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal -> R$25.00", "Elétrica -> R$45.00" }));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblValorTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValorTotal.setText("Valor Total");

        ftfValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfValorTotalActionPerformed(evt);
            }
        });

        ftfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        ftfDataDevolucao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTipoPessoa)
                            .addComponent(lblBicicleta)
                            .addComponent(lblDataInicio)
                            .addComponent(lblDataDevolucao)
                            .addComponent(lblValorTotal))
                        .addGap(18, 18, 18)
                        .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ftfDataDevolucao)
                            .addComponent(cmbTipoPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbBicicleta, 0, 267, Short.MAX_VALUE)
                            .addComponent(ftfDataInicio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ftfValorTotal)))
                    .addGroup(PrincipalLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoPessoa))
                .addGap(18, 18, 18)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBicicleta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBicicleta))
                .addGap(18, 18, 18)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataInicio))
                .addGap(18, 18, 18)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfDataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataDevolucao))
                .addGap(42, 42, 42)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftfValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotal))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        int tipoPessoa = cmbTipoPessoa.getSelectedIndex();
        int bicicleta = cmbBicicleta.getSelectedIndex();
        LocalDate dataDevolucao1 = LocalDate.parse(ftfDataDevolucao.getText(), formatter);
        LocalDate dataInicio1 = LocalDate.parse(ftfDataInicio.getText(), formatter);

        Calcular calcular = new Calcular(tipoPessoa, bicicleta, dataInicio1, dataDevolucao1);

        double valorTotal = calcular.CalcularValorTotal();
        
        ftfValorTotal.setText(String.format("R$%2f", valorTotal));
        ftfValorTotal.setEditable(false);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void ftfValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfValorTotalActionPerformed

    }//GEN-LAST:event_ftfValorTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cmbBicicleta;
    private javax.swing.JComboBox<String> cmbTipoPessoa;
    private javax.swing.JFormattedTextField ftfDataDevolucao;
    private javax.swing.JFormattedTextField ftfDataInicio;
    private javax.swing.JFormattedTextField ftfValorTotal;
    private javax.swing.JLabel lblBicicleta;
    private javax.swing.JLabel lblDataDevolucao;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JLabel lblValorTotal;
    // End of variables declaration//GEN-END:variables
}
